#!/bin/sh
#
# This script compiles and links and the binary
# We do some elf parsing here because we need to know the 
# hyplet size in advance.
#sudo kpartx -a /opt/truly/linaro_fvp/armv8.img
#
GCC=gcc-linaro-4.9-2015.05-x86_64_aarch64-linux-gnu
CC=/opt/${GCC}/bin/aarch64-linux-gnu-gcc 
READELF=/opt/${GCC}/bin/aarch64-linux-gnu-readelf
OBJDUMP=/opt/${GCC}/bin/aarch64-linux-gnu-objdump
STRIP=/opt/${GCC}/bin/aarch64-linux-gnu-strip

#
# c-flat
#
$CC --static  -I ../../../../include cflat-rpc.c hyplet_utilsS.S hyplet_utils.c -o cflat
