#!/bin/sh
#
GCC=/opt/gcc-linaro-4.9-2015.05-x86_64_aarch64-linux-gnu/
CC=${GCC}/bin/aarch64-linux-gnu-gcc 
CC32=/opt/raspberry/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
READELF=/${GCC}/bin/aarch64-linux-gnu-readelf
OBJDUMP=${GCC}/bin/aarch64-linux-gnu-objdump
STRIP=${GCC}/bin/aarch64-linux-gnu-strip
