#!/bin/sh
#
# This script compiles and links and the binary
GCC=/opt/gcc-linaro-4.9-2015.05-x86_64_aarch64-linux-gnu/
CC=${GCC}/bin/aarch64-linux-gnu-gcc 
READELF=/opt/${GCC}/bin/aarch64-linux-gnu-readelf
OBJDUMP=/opt/${GCC}/bin/aarch64-linux-gnu-objdump
#
$CC unknown_opcode.c \
	hyplet_utils.c \
	hyplet_utilsS.S \
	elf.c \
	-o unknowncode

$CC f.s hyplet_utils.c hyplet_utilsS.S  offlet_unknown_opcode.c -o offunkn
