#!/bin/sh
#
# This script compiles and links and the binary

sudo kpartx -a /opt/truly/linaro_fvp/armv8.img
#
GCC=/opt/gcc-linaro-4.9-2015.05-x86_64_aarch64-linux-gnu/
CC=${GCC}/bin/aarch64-linux-gnu-gcc 
READELF=/opt/${GCC}/bin/aarch64-linux-gnu-readelf
OBJDUMP=/opt/${GCC}/bin/aarch64-linux-gnu-objdump
#
$CC unknown_opcode.c \
	hyplet_utils.c \
	hyplet_utilsS.S \
	elf.c \
	-o unknowncode

mkdir -p /tmp/fvp/
sudo mount /dev/mapper/loop0p2 /tmp/fvp
sudo cp  unknowncode /tmp/fvp//home/root/
sudo umount /tmp/fvp
sudo kpartx -d /opt/truly/linaro_fvp/armv8.img
