#
# Makefile for Truly
#  memory_layout.o \
#

obj-$(CONFIG_HYPLET) += ImageManager.o \
	ImageFile_linux.o \
	memory_layout.o \
	intervals.o \
	vector.o \
	common.o \
	elf.o \
	linux_kernfile.o \
	tpdriver.o
