#
# Makefile for Truly
#
#asflags-y  := "-march=armv8.1-a"

obj-$(CONFIG_TRULY_PROTECT) += trulyS.o truly.o \
	tpdriver.o \
	ImageManager.o \
	osal_linux.o \
	common.o \
    intervals.o \
    vector.o \
    memory_layout.o \
	tp_mmu.o \
	log_linux.o \
	linux_kernfile.o \
	ImageFile_linux.o \
	truly_user.o \
	Aes.o \
	elf.o
